/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_sim;

import java.awt.Color;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Jiayun
 */
public class Restaurant_Auth_Client_GUI extends javax.swing.JFrame {
    private Restaurant_Auth_Client rAuthClient;
    /**
     * Creates new form Restaurant_Auth_Client_GUI
     */
    public Restaurant_Auth_Client_GUI() {
        rAuthClient = new Restaurant_Auth_Client();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton_t0 = new javax.swing.JButton();
        jButton_t1 = new javax.swing.JButton();
        jButton_t2 = new javax.swing.JButton();
        jButton_t3 = new javax.swing.JButton();
        jButton_t4 = new javax.swing.JButton();
        jButton_t5 = new javax.swing.JButton();
        jButton_t6 = new javax.swing.JButton();
        jButton_t7 = new javax.swing.JButton();
        jButton_t8 = new javax.swing.JButton();
        jButton_t9 = new javax.swing.JButton();
        jButton_t10 = new javax.swing.JButton();
        jButton_t11 = new javax.swing.JButton();
        jButton_t12 = new javax.swing.JButton();
        jButton_t13 = new javax.swing.JButton();
        jButton_t14 = new javax.swing.JButton();
        jButton_t15 = new javax.swing.JButton();
        jButton_t16 = new javax.swing.JButton();
        jButton_t17 = new javax.swing.JButton();
        jButton_t18 = new javax.swing.JButton();
        jButton_t19 = new javax.swing.JButton();
        jButton_t20 = new javax.swing.JButton();
        jButton_t21 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Client ");

        jLabel2.setText("Authorized Access");

        jLabel3.setText("Please log in to get control");

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });

        jButton_login.setText("LOGIN");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel5))
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton_login))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton_login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_t0.setText("open");
        jButton_t0.setBackground(Color.GREEN);
        jButton_t1.setBackground(Color.GREEN);
        jButton_t2.setBackground(Color.GREEN);
        jButton_t3.setBackground(Color.GREEN);
        jButton_t4.setBackground(Color.GREEN);
        jButton_t5.setBackground(Color.GREEN);
        jButton_t6.setBackground(Color.GREEN);
        jButton_t7.setBackground(Color.GREEN);
        jButton_t8.setBackground(Color.GREEN);
        jButton_t9.setBackground(Color.GREEN);
        jButton_t10.setBackground(Color.GREEN);
        jButton_t11.setBackground(Color.GREEN);
        jButton_t12.setBackground(Color.GREEN);
        jButton_t13.setBackground(Color.GREEN);
        jButton_t14.setBackground(Color.GREEN);
        jButton_t15.setBackground(Color.GREEN);
        jButton_t16.setBackground(Color.GREEN);
        jButton_t17.setBackground(Color.GREEN);
        jButton_t18.setBackground(Color.GREEN);
        jButton_t19.setBackground(Color.GREEN);
        jButton_t20.setBackground(Color.GREEN);
        jButton_t21.setBackground(Color.GREEN);
        jButton_t0.setName("0");
        jButton_t1.setName("1");
        jButton_t2.setName("2");
        jButton_t3.setName("3");
        jButton_t4.setName("4");
        jButton_t5.setName("5");
        jButton_t6.setName("6");
        jButton_t7.setName("7");
        jButton_t8.setName("8");
        jButton_t9.setName("9");
        jButton_t10.setName("10");
        jButton_t11.setName("11");
        jButton_t12.setName("12");
        jButton_t13.setName("13");
        jButton_t14.setName("14");
        jButton_t15.setName("15");
        jButton_t16.setName("16");
        jButton_t17.setName("17");
        jButton_t18.setName("18");
        jButton_t19.setName("19");
        jButton_t20.setName("20");
        jButton_t21.setName("21");
        jButton_t0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t0ActionPerformed(evt);
            }
        });

        jButton_t1.setText("open");
        jButton_t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t1ActionPerformed(evt);
            }
        });

        jButton_t2.setText("open");
        jButton_t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t2ActionPerformed(evt);
            }
        });

        jButton_t3.setText("open");
        jButton_t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t3ActionPerformed(evt);
            }
        });

        jButton_t4.setText("open");
        jButton_t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t4ActionPerformed(evt);
            }
        });

        jButton_t5.setText("open");
        jButton_t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t5ActionPerformed(evt);
            }
        });

        jButton_t6.setText("open");
        jButton_t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t6ActionPerformed(evt);
            }
        });

        jButton_t7.setText("open");
        jButton_t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t7ActionPerformed(evt);
            }
        });

        jButton_t8.setText("open");
        jButton_t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t8ActionPerformed(evt);
            }
        });

        jButton_t9.setText("open");
        jButton_t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t9ActionPerformed(evt);
            }
        });

        jButton_t10.setText("open");
        jButton_t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t10ActionPerformed(evt);
            }
        });

        jButton_t11.setText("open");
        jButton_t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t11ActionPerformed(evt);
            }
        });

        jButton_t12.setText("open");
        jButton_t12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t12ActionPerformed(evt);
            }
        });

        jButton_t13.setText("open");
        jButton_t13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t13ActionPerformed(evt);
            }
        });

        jButton_t14.setText("open");
        jButton_t14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t14ActionPerformed(evt);
            }
        });

        jButton_t15.setText("open");
        jButton_t15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t15ActionPerformed(evt);
            }
        });

        jButton_t16.setText("open");
        jButton_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t16ActionPerformed(evt);
            }
        });

        jButton_t17.setText("open");
        jButton_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t17ActionPerformed(evt);
            }
        });

        jButton_t18.setText("open");
        jButton_t18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t18ActionPerformed(evt);
            }
        });

        jButton_t19.setText("open");
        jButton_t19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t19ActionPerformed(evt);
            }
        });

        jButton_t20.setText("open");
        jButton_t20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t20ActionPerformed(evt);
            }
        });

        jButton_t21.setText("open");
        jButton_t21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_t21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_t0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_t1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_t2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_t3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_t4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_t5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_t6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_t7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_t8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_t9))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton_t10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_t11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_t12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_t13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_t14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_t15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_t16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_t17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_t18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_t19)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_t20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_t21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_t0)
                    .addComponent(jButton_t1)
                    .addComponent(jButton_t2)
                    .addComponent(jButton_t3)
                    .addComponent(jButton_t4))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_t5)
                    .addComponent(jButton_t6)
                    .addComponent(jButton_t7)
                    .addComponent(jButton_t8)
                    .addComponent(jButton_t9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_t10)
                    .addComponent(jButton_t11)
                    .addComponent(jButton_t12)
                    .addComponent(jButton_t13))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_t14)
                    .addComponent(jButton_t15)
                    .addComponent(jButton_t16)
                    .addComponent(jButton_t17)
                    .addComponent(jButton_t18))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_t19)
                    .addComponent(jButton_t20)
                    .addComponent(jButton_t21))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jLabel6.setText("Size 2");

        jLabel7.setText("Size 4");

        jLabel8.setText("Size 6");

        jLabel9.setText("Size 8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel7)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel8)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        if(rAuthClient.getAuth(jTextField_username.getText(), String.valueOf(jPasswordField1.getPassword())))
            System.out.println("Login in successfully!");
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jButton_t0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t0ActionPerformed
        try {
            myActionPerform((JButton)evt.getSource());
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t0ActionPerformed

    private void jButton_t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t1ActionPerformed
        try {
            myActionPerform(jButton_t1);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t1ActionPerformed

    private void jButton_t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t2ActionPerformed
        try {
            myActionPerform(jButton_t2);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t2ActionPerformed

    private void jButton_t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t3ActionPerformed
        try {
            myActionPerform(jButton_t3);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t3ActionPerformed

    private void jButton_t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t4ActionPerformed
        try {
            myActionPerform(jButton_t4);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t4ActionPerformed

    private void jButton_t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t5ActionPerformed
        try {
            myActionPerform(jButton_t5);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t5ActionPerformed

    private void jButton_t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t6ActionPerformed
        try {
            myActionPerform(jButton_t6);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t6ActionPerformed

    private void jButton_t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t7ActionPerformed
        try {
            myActionPerform(jButton_t7);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t7ActionPerformed

    private void jButton_t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t8ActionPerformed
        try {
            myActionPerform(jButton_t8);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t8ActionPerformed

    private void jButton_t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t9ActionPerformed
        try {
            myActionPerform(jButton_t9);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t9ActionPerformed

    private void jButton_t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t10ActionPerformed
        try {
            myActionPerform(jButton_t10);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t10ActionPerformed

    private void jButton_t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t11ActionPerformed
        try {
            myActionPerform(jButton_t11);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t11ActionPerformed

    private void jButton_t12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t12ActionPerformed
        try {
            myActionPerform(jButton_t12);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t12ActionPerformed

    private void jButton_t13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t13ActionPerformed
        try {
            myActionPerform(jButton_t13);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t13ActionPerformed

    private void jButton_t14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t14ActionPerformed
        try {
            myActionPerform(jButton_t14);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t14ActionPerformed

    private void jButton_t15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t15ActionPerformed
        try {
            myActionPerform(jButton_t15);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t15ActionPerformed

    private void jButton_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t16ActionPerformed
        try {
            myActionPerform(jButton_t16);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t16ActionPerformed

    private void jButton_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t17ActionPerformed
        try {
            myActionPerform(jButton_t17);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t17ActionPerformed

    private void jButton_t18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t18ActionPerformed
        try {
            myActionPerform(jButton_t18);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t18ActionPerformed

    private void jButton_t19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t19ActionPerformed
        try {
            myActionPerform(jButton_t19);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t19ActionPerformed

    private void jButton_t20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t20ActionPerformed
        try {
            myActionPerform(jButton_t20);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t20ActionPerformed

    private void jButton_t21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_t21ActionPerformed
        try {
            myActionPerform(jButton_t21);
        } catch (RemoteException ex) {
            Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_t21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Auth_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant_Auth_Client_GUI().setVisible(true);
            }
        });
      
    }
    
    private void myActionPerform(JButton button) throws RemoteException{
        String temp = button.getName();
        int tblNumber = Integer.valueOf(temp);
        if(button.getText().equals("open")){
            if(rAuthClient.closeTable(tblNumber)){
                button.setText("closed");
                button.setBackground(Color.red);
            }
        }
        else if(button.getText().equals("closed")){
            if(rAuthClient.openTable(tblNumber)){
                button.setText("open");
                button.setBackground(Color.GREEN);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login;
    private javax.swing.JButton jButton_t0;
    private javax.swing.JButton jButton_t1;
    private javax.swing.JButton jButton_t10;
    private javax.swing.JButton jButton_t11;
    private javax.swing.JButton jButton_t12;
    private javax.swing.JButton jButton_t13;
    private javax.swing.JButton jButton_t14;
    private javax.swing.JButton jButton_t15;
    private javax.swing.JButton jButton_t16;
    private javax.swing.JButton jButton_t17;
    private javax.swing.JButton jButton_t18;
    private javax.swing.JButton jButton_t19;
    private javax.swing.JButton jButton_t2;
    private javax.swing.JButton jButton_t20;
    private javax.swing.JButton jButton_t21;
    private javax.swing.JButton jButton_t3;
    private javax.swing.JButton jButton_t4;
    private javax.swing.JButton jButton_t5;
    private javax.swing.JButton jButton_t6;
    private javax.swing.JButton jButton_t7;
    private javax.swing.JButton jButton_t8;
    private javax.swing.JButton jButton_t9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
