/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_sim;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

public class Restaurant_GUI extends javax.swing.JFrame {

    private final int customer_TOTAL = 400;
    private final int waiter_TOTAL = 5;
    private final int restaurant_CAPACITY = 100;
    private final int table_TOTAL = 22;
    private static Restaurant r;
    private static Timer timer_waiting;
    private static Timer timer_entered;
    private static Timer timer_table;
    private static Timer timer_waiter;
    private static Timer timer_log;
    private boolean running;

    /**
     * Creates new form Restaurant_GUI
     */
    public Restaurant_GUI() {
        running = true;
        r = new Restaurant(customer_TOTAL, waiter_TOTAL, table_TOTAL, restaurant_CAPACITY,running);
        timer_waiting = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                refresh_waiting();
            }
        });
        timer_entered = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                refresh_entered();
            }
        });
        timer_table = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                refresh_table();
            }
        });
        timer_waiter = new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               refresh_waiter();
            }
        });
        timer_log = new  Timer(3000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                refresh_log();
            }
        });
        initComponents();    
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Customer = new javax.swing.JPanel();
        jLabel_Customer = new javax.swing.JLabel();
        jPanel_Waiting = new javax.swing.JPanel();
        jLabel_Waiting = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Waiting = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Entered = new javax.swing.JTextArea();
        jLabel_Entered = new javax.swing.JLabel();
        jPanel_Waiter = new javax.swing.JPanel();
        jLabel_Waiter = new javax.swing.JLabel();
        jLabel_Head_Waiter = new javax.swing.JLabel();
        jTextField_Head_Waiter = new javax.swing.JTextField();
        jLabel_w1 = new javax.swing.JLabel();
        jLabel_w2 = new javax.swing.JLabel();
        jLabel_w3 = new javax.swing.JLabel();
        jLabel_w4 = new javax.swing.JLabel();
        jLabel_w5 = new javax.swing.JLabel();
        jTextField_w1 = new javax.swing.JTextField();
        jTextField_w2 = new javax.swing.JTextField();
        jTextField_w3 = new javax.swing.JTextField();
        jTextField_w4 = new javax.swing.JTextField();
        jTextField_w5 = new javax.swing.JTextField();
        jPanel_Tables = new javax.swing.JPanel();
        jLabel_Table = new javax.swing.JLabel();
        jPanel_ts2 = new javax.swing.JPanel();
        jLabel_ts2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_ts2 = new javax.swing.JTextArea();
        jPanel_ts4 = new javax.swing.JPanel();
        jLabel_ts4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_ts4 = new javax.swing.JTextArea();
        jPanel_ts8 = new javax.swing.JPanel();
        jLabel_ts8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea_ts8 = new javax.swing.JTextArea();
        jPanel_ts6 = new javax.swing.JPanel();
        jLabel_ts6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea_ts6 = new javax.swing.JTextArea();
        jPanel_Control = new javax.swing.JPanel();
        jButton_resume = new javax.swing.JButton();
        jButton_pause = new javax.swing.JButton();
        jLabel_Control = new javax.swing.JLabel();
        jPanel_log = new javax.swing.JPanel();
        jLabel_log = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea_log = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Customer.setText("CUSTOMER");
        jLabel_Customer.setFont(new Font("Agency FB", Font.PLAIN, 30));

        jLabel_Waiting.setText("Waiting");

        jTextArea_Waiting.setColumns(20);
        jTextArea_Waiting.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Waiting);

        javax.swing.GroupLayout jPanel_WaitingLayout = new javax.swing.GroupLayout(jPanel_Waiting);
        jPanel_Waiting.setLayout(jPanel_WaitingLayout);
        jPanel_WaitingLayout.setHorizontalGroup(
            jPanel_WaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WaitingLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel_Waiting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
            .addGroup(jPanel_WaitingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel_WaitingLayout.setVerticalGroup(
            jPanel_WaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WaitingLayout.createSequentialGroup()
                .addComponent(jLabel_Waiting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextArea_Entered.setColumns(20);
        jTextArea_Entered.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Entered);

        jLabel_Entered.setText("Entered");

        javax.swing.GroupLayout jPanel_CustomerLayout = new javax.swing.GroupLayout(jPanel_Customer);
        jPanel_Customer.setLayout(jPanel_CustomerLayout);
        jPanel_CustomerLayout.setHorizontalGroup(
            jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                .addComponent(jPanel_Waiting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CustomerLayout.createSequentialGroup()
                        .addComponent(jLabel_Entered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50))))
            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel_Customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_CustomerLayout.setVerticalGroup(
            jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                .addComponent(jLabel_Customer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Waiting, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_CustomerLayout.createSequentialGroup()
                        .addComponent(jLabel_Entered)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel_Waiter.setText("WAITER");
        jLabel_Waiter.setFont(new Font("Agency FB", Font.PLAIN, 30));

        jLabel_Head_Waiter.setText("Head Waiter Status:");

        jTextField_Head_Waiter.setText("jTextField1");

        jLabel_w1.setText("Waiter 1");

        jLabel_w2.setText("Waiter 2");

        jLabel_w3.setText("Waiter 3");

        jLabel_w4.setText("Waiter 4");

        jLabel_w5.setText("Waiter 5");

        jTextField_w1.setText("jTextField1");

        jTextField_w2.setText("jTextField2");

        jTextField_w3.setText("jTextField3");

        jTextField_w4.setText("jTextField4");

        jTextField_w5.setText("jTextField5");

        javax.swing.GroupLayout jPanel_WaiterLayout = new javax.swing.GroupLayout(jPanel_Waiter);
        jPanel_Waiter.setLayout(jPanel_WaiterLayout);
        jPanel_WaiterLayout.setHorizontalGroup(
            jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WaiterLayout.createSequentialGroup()
                .addGroup(jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_WaiterLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel_Waiter)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_WaiterLayout.createSequentialGroup()
                        .addGroup(jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Head_Waiter)
                            .addGroup(jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel_w5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_w4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_w3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_w2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_w1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Head_Waiter, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jTextField_w1)
                            .addComponent(jTextField_w2)
                            .addComponent(jTextField_w3)
                            .addComponent(jTextField_w4)
                            .addComponent(jTextField_w5))))
                .addContainerGap())
        );
        jPanel_WaiterLayout.setVerticalGroup(
            jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WaiterLayout.createSequentialGroup()
                .addComponent(jLabel_Waiter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Head_Waiter)
                    .addComponent(jTextField_Head_Waiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_w1)
                    .addComponent(jTextField_w1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_w2)
                    .addComponent(jTextField_w2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_w3)
                    .addComponent(jTextField_w3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_w4)
                    .addComponent(jTextField_w4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_WaiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_w5)
                    .addComponent(jTextField_w5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel_Table.setText("TABLES");
        jLabel_Table.setFont(new Font("Agency FB", Font.PLAIN, 30));

        jLabel_ts2.setText("Size 2");

        jTextArea_ts2.setColumns(20);
        jTextArea_ts2.setRows(5);
        jScrollPane4.setViewportView(jTextArea_ts2);

        javax.swing.GroupLayout jPanel_ts2Layout = new javax.swing.GroupLayout(jPanel_ts2);
        jPanel_ts2.setLayout(jPanel_ts2Layout);
        jPanel_ts2Layout.setHorizontalGroup(
            jPanel_ts2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ts2Layout.createSequentialGroup()
                .addComponent(jLabel_ts2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
        );
        jPanel_ts2Layout.setVerticalGroup(
            jPanel_ts2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ts2Layout.createSequentialGroup()
                .addComponent(jLabel_ts2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_ts4.setText("Size 4");

        jTextArea_ts4.setColumns(20);
        jTextArea_ts4.setRows(5);
        jScrollPane5.setViewportView(jTextArea_ts4);

        javax.swing.GroupLayout jPanel_ts4Layout = new javax.swing.GroupLayout(jPanel_ts4);
        jPanel_ts4.setLayout(jPanel_ts4Layout);
        jPanel_ts4Layout.setHorizontalGroup(
            jPanel_ts4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ts4Layout.createSequentialGroup()
                .addComponent(jLabel_ts4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane5)
        );
        jPanel_ts4Layout.setVerticalGroup(
            jPanel_ts4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ts4Layout.createSequentialGroup()
                .addComponent(jLabel_ts4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_ts8.setText("Size 8");

        jTextArea_ts8.setColumns(20);
        jTextArea_ts8.setRows(5);
        jScrollPane7.setViewportView(jTextArea_ts8);

        javax.swing.GroupLayout jPanel_ts8Layout = new javax.swing.GroupLayout(jPanel_ts8);
        jPanel_ts8.setLayout(jPanel_ts8Layout);
        jPanel_ts8Layout.setHorizontalGroup(
            jPanel_ts8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ts8Layout.createSequentialGroup()
                .addComponent(jLabel_ts8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );
        jPanel_ts8Layout.setVerticalGroup(
            jPanel_ts8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ts8Layout.createSequentialGroup()
                .addComponent(jLabel_ts8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_ts6.setText("Size 6");

        jTextArea_ts6.setColumns(20);
        jTextArea_ts6.setRows(5);
        jScrollPane6.setViewportView(jTextArea_ts6);

        javax.swing.GroupLayout jPanel_ts6Layout = new javax.swing.GroupLayout(jPanel_ts6);
        jPanel_ts6.setLayout(jPanel_ts6Layout);
        jPanel_ts6Layout.setHorizontalGroup(
            jPanel_ts6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ts6Layout.createSequentialGroup()
                .addComponent(jLabel_ts6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );
        jPanel_ts6Layout.setVerticalGroup(
            jPanel_ts6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ts6Layout.createSequentialGroup()
                .addComponent(jLabel_ts6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_TablesLayout = new javax.swing.GroupLayout(jPanel_Tables);
        jPanel_Tables.setLayout(jPanel_TablesLayout);
        jPanel_TablesLayout.setHorizontalGroup(
            jPanel_TablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TablesLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel_Table)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_TablesLayout.createSequentialGroup()
                .addGroup(jPanel_TablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TablesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel_ts6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel_ts2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_TablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_ts8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_ts4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_TablesLayout.setVerticalGroup(
            jPanel_TablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TablesLayout.createSequentialGroup()
                .addComponent(jLabel_Table)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_TablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_ts4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_ts2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_TablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_ts6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_ts8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton_resume.setText("Resume");
        jButton_resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resumeActionPerformed(evt);
            }
        });

        jButton_pause.setText("Pause");
        jButton_pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pauseActionPerformed(evt);
            }
        });

        jLabel_Control.setText("Control Panel");
        jLabel_Control.setFont(new Font("Agency FB", Font.PLAIN, 30));

        javax.swing.GroupLayout jPanel_ControlLayout = new javax.swing.GroupLayout(jPanel_Control);
        jPanel_Control.setLayout(jPanel_ControlLayout);
        jPanel_ControlLayout.setHorizontalGroup(
            jPanel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ControlLayout.createSequentialGroup()
                .addGroup(jPanel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ControlLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton_resume)
                        .addGap(85, 85, 85)
                        .addComponent(jButton_pause))
                    .addGroup(jPanel_ControlLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel_Control)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel_ControlLayout.setVerticalGroup(
            jPanel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ControlLayout.createSequentialGroup()
                .addComponent(jLabel_Control)
                .addGap(18, 18, 18)
                .addGroup(jPanel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_pause, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton_resume, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel_log.setText("LOG");

        jTextArea_log.setColumns(20);
        jTextArea_log.setRows(5);
        jScrollPane8.setViewportView(jTextArea_log);

        javax.swing.GroupLayout jPanel_logLayout = new javax.swing.GroupLayout(jPanel_log);
        jPanel_log.setLayout(jPanel_logLayout);
        jPanel_logLayout.setHorizontalGroup(
            jPanel_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
            .addGroup(jPanel_logLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel_log)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel_logLayout.setVerticalGroup(
            jPanel_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_logLayout.createSequentialGroup()
                .addComponent(jLabel_log)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Waiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_Control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel_Customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(jPanel_Tables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(jPanel_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Waiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_Tables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_resumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resumeActionPerformed
        r.resumeAll();
    }//GEN-LAST:event_jButton_resumeActionPerformed

    private void jButton_pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pauseActionPerformed
        r.suspendAll();
    }//GEN-LAST:event_jButton_pauseActionPerformed

    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Restaurant_GUI().setVisible(true);
                timer_waiting.start();
                timer_entered.start();
                timer_table.start();
                timer_waiter.start();
                timer_log.start();
            }
        });
    }
    private void refresh_waiting(){
        jTextArea_Waiting.setText(r.waitingToString());
    }
    
    private void refresh_entered(){
        jTextArea_Entered.setText(r.enteredToString());
    }
    
    private void refresh_table(){
        String result[] = r.tableToString();
        jTextArea_ts2.setText(result[0]);
        jTextArea_ts4.setText(result[1]);
        jTextArea_ts6.setText(result[2]);
        jTextArea_ts8.setText(result[3]);
    }
    
    private void refresh_waiter(){
        String waiterString[] = r.waiterToString();
        jTextField_Head_Waiter.setText(r.headWaiterToString());
        jTextField_w1.setText(waiterString[0]);
        jTextField_w2.setText(waiterString[1]);
        jTextField_w3.setText(waiterString[2]);
        jTextField_w4.setText(waiterString[3]);
        jTextField_w5.setText(waiterString[4]);
        
    }
    private void refresh_log(){
        jTextArea_log.setText(r.logToString());
    }
    public String getLog(){
        return r.logToString();
    }
    public boolean authenticate(String username, String password){
        return r.verify(username, password);
    }
    
    public boolean closeTable(int tableID){
        return r.closeTable(tableID);
    }
    
    public boolean openTable(int tableID){
        return r.openTable(tableID);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_pause;
    private javax.swing.JButton jButton_resume;
    private javax.swing.JLabel jLabel_Control;
    private javax.swing.JLabel jLabel_Customer;
    private javax.swing.JLabel jLabel_Entered;
    private javax.swing.JLabel jLabel_Head_Waiter;
    private javax.swing.JLabel jLabel_Table;
    private javax.swing.JLabel jLabel_Waiter;
    private javax.swing.JLabel jLabel_Waiting;
    private javax.swing.JLabel jLabel_log;
    private javax.swing.JLabel jLabel_ts2;
    private javax.swing.JLabel jLabel_ts4;
    private javax.swing.JLabel jLabel_ts6;
    private javax.swing.JLabel jLabel_ts8;
    private javax.swing.JLabel jLabel_w1;
    private javax.swing.JLabel jLabel_w2;
    private javax.swing.JLabel jLabel_w3;
    private javax.swing.JLabel jLabel_w4;
    private javax.swing.JLabel jLabel_w5;
    private javax.swing.JPanel jPanel_Control;
    private javax.swing.JPanel jPanel_Customer;
    private javax.swing.JPanel jPanel_Tables;
    private javax.swing.JPanel jPanel_Waiter;
    private javax.swing.JPanel jPanel_Waiting;
    private javax.swing.JPanel jPanel_log;
    private javax.swing.JPanel jPanel_ts2;
    private javax.swing.JPanel jPanel_ts4;
    private javax.swing.JPanel jPanel_ts6;
    private javax.swing.JPanel jPanel_ts8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea_Entered;
    private javax.swing.JTextArea jTextArea_Waiting;
    private javax.swing.JTextArea jTextArea_log;
    private javax.swing.JTextArea jTextArea_ts2;
    private javax.swing.JTextArea jTextArea_ts4;
    private javax.swing.JTextArea jTextArea_ts6;
    private javax.swing.JTextArea jTextArea_ts8;
    private javax.swing.JTextField jTextField_Head_Waiter;
    private javax.swing.JTextField jTextField_w1;
    private javax.swing.JTextField jTextField_w2;
    private javax.swing.JTextField jTextField_w3;
    private javax.swing.JTextField jTextField_w4;
    private javax.swing.JTextField jTextField_w5;
    // End of variables declaration//GEN-END:variables
}
